# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "lighter-ccxt-adapter"
VERSION = "0.1"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "python-dotenv",
    "ccxt",
    "aiohttp == 3.9.3",
]

setup(
    name=NAME,
    version=VERSION,
    description="Python CCXT Wrapper for lighter.xyz",
    author="marcelkb",
    author_email="",
    url="",
    keywords=["lighter", "ccxt", ""],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
    Python CCXT Wrapper for Lighter trading.
    """,  # noqa: E501
    package_data={"lighter": ["py.typed", "signers/*"]},
)
